### ISSUE TITLE
[News] Images on detail pages for news

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#103]
The images for the detail page for a News are small for desktop. Could we put them the on top of text? If in your opinion it will not look good, we'll keep as it is right now.

**Comment by mcgarciawq** [comment]
WIP. I'm going to do some changes to put this detail like a Session detail.

**Comment by mcgarciawq** [comment]
Done! Thanks for the issue, now you can review it the entire detail page :)

**Comment by jlbellido** [comment]
Solved! Thanks @keilovecraft !
