### ISSUE TITLE
[Global] Sidebar menus

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#106]
We need to implement the sidebars menus for the website.
Concrete tasks:

Backend:
- [x] Create a new menu a place it at the sidebar region.
- [x] Create a new menu a place it at the second sidebar region.

Frontend:
- [x] Customize the page templates accordingly.
- [x] Apply the styles according the design https://projects.invisionapp.com/share/7K9PLICYJ#/screens/210910508.

**How to work on this?**
- Create a new branch from your dev branch like an other normal ticket.
- Fetch the changes introduced in  the other branch: git pull https://github.com/jlbellido/devdaysseville.git 106_sidebar_menus
- import the new configuration : (from web folder) drush cim -y
- Create a menu item for the left side menu at admin/structure/menu/manage/left-side-menu
- Commit your changes from the front end part.
- Push your changes as usual and send a pull request.
- You will notice that all commits will be there (yours and that ones done previously)

**Comment by jlbellido** [comment]
I'm starting with this.

**Comment by jlbellido** [comment]
Now the front-end part is not blocked.

**Comment by Nesta** [comment]
WIP

**Comment by Nesta** [comment]
Done!

**Comment by jlbellido** [comment]
Checked and it is fine from my side. Thanks @Nesta for such as awesome work!
![106_sidebar_menus](https://cloud.githubusercontent.com/assets/1301237/22350231/4c268dc0-e413-11e6-962e-b81eddb34c14.png)
