### ISSUE TITLE
[Home] Home menu of the first stage

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#107]
Follow-up to #68 

We need to add the styles needed to the home menu at the first stage.
![home_menu_issue](https://cloud.githubusercontent.com/assets/1301237/22038022/e1ac8028-dcf9-11e6-862c-fbeaf3bad2ed.png)

**Comment by babette-landmesser** [comment]
I start styling the buttons.

**Comment by jlbellido** [comment]
Solved, thanks @babette-landmesser
