### ISSUE TITLE
[Global] Links on basic pages styles.

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#109]
The styles for normal links at the basic pages are not different from the normal text. At least it is diffictult to differentiate.

**How to reproduce**
- Create a basic page
- On the body field, set a link using the WYSYWYG and save.
- Check that is hard to differentiate from the normal text.

**Comment by tbeenpwn** [comment]
Working on it!

**Comment by jlbellido** [comment]
Merged! Thanks @tbeenpwn !!
