### ISSUE TITLE
[Sponsors] Background image at sponsors page

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#122]
![sponsors - drupal dev days sevilla 2017 2017-01-19 22-36-15](https://cloud.githubusercontent.com/assets/1301237/22174032/2e3b3db2-dfd4-11e6-949f-34a70a8d261b.png)

**Comment by jmfegu** [comment]
Work in progress

**Comment by mcgarciawq** [comment]
@jmfernandezemergya some news about this task?

**Comment by keilovecraft** [comment]
@jmfernandezemergya ?

**Comment by jmfegu** [comment]
@keilovecraft. Sorry I have tried to work in this issue but I don't have a break lately.

**Comment by mcgarciawq** [comment]
@jlbellido the addition of new sponsors fixed this problem (because the height has grown 🗡 ). Can you review it again, please?

**Comment by jlbellido** [comment]
![screenshot-seville2017 drupaldays org-2017-03-01-20-35-55](https://cloud.githubusercontent.com/assets/1301237/23477573/ba0e1680-febe-11e6-81cf-19cf44cfa25a.png)

I've checked it and it is fixed now. Thanks to both of you! Without you this ship is going to nowhere!
