### ISSUE TITLE
[Sponsors] Titles font size for bronze and silver.

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#124]
> gold sponsors h2 font-size is smaller than the rest at http://seville2017.drupaldays.org/sponsors

Thanks @penyaskito for reporting.

**Comment by Nesta** [comment]
Work in progress

**Comment by rafavermo** [comment]
For me. I work in progress.

**Comment by jlbellido** [comment]
It's fixed now, thanks @rafavermo for your work here!

Here is the attached screenshot.
![124_sponosrs_titles](https://cloud.githubusercontent.com/assets/1301237/22332840/440f9f36-e3d3-11e6-97d7-a297eaaf2e4c.png)
