### ISSUE TITLE
[Keynotes] Keynote detail page

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#164]
We need a section for the featured speakers of the event.
For this section we need the following changes:

- New content type: Keynote with the following fields:
  - Keynote Title.
  - Keynote description.
  - Group: The speaker
    - Speaker name
    - Speaker possition
    - Speaker Bio
    - Speaker picture
  - Group: The company
    - The company name
    - The company description.
    - The company picture.

- Configure the teaser and full view mode.

**How to reproduce**
- Use devel generate for generate automatically several "Keynote" nodes.

**Comment by jlbellido** [comment]
I'm starting this

**Comment by jlbellido** [comment]
Done the backend part
Update the summary with the "how to reproduce"

**Comment by mcgarciawq** [comment]
WIP

**Comment by mcgarciawq** [comment]
Done! Waiting for date field.
