### ISSUE TITLE
[Keynotes] List of Keynotes

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#165]
We need to add list of the keynotes of the event at : program/keynotes path

It will use the teaser view mode of key notes content type.

**How to reproduce**
- Create several nodes of Keynote content type.
- Go to /program/keynotes path

**Comment by jlbellido** [comment]
Configured the teaser view mode and created a view lit for this. This is ready for being styled.

**Comment by mcgarciawq** [comment]
Styles done! Waiting for the date field.
