### ISSUE TITLE
[Global] Responsive menu with scroll

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#188]
We are reaching the max number of menu items to be desplayed in the responsive menu. We need to provide a solution for solving this problem we will have in the future.

**Comment by jlbellido** [comment]
Would be possible / good to add an scroll bar?

**Comment by rafavermo** [comment]
WIP

**Comment by mcgarciawq** [comment]
@rafavermo review the styles for menu in screens between 700-800px

**Comment by jlbellido** [comment]
@keilovecraft can I close this task or is there something needed here?

**Comment by mcgarciawq** [comment]
Need more work. 

@rafavermo are you with this task?

**Comment by rafavermo** [comment]
Done!

**Comment by mcgarciawq** [comment]
@jlbellido this task is ready to be closed!
