### ISSUE TITLE
[Sponsors] Individual sponsors

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#191]
We need a section for the individual sponsors. We would need the following changes:

- [x] New role "Individual sponsor" without any special permissions, just the rol.
- [x] Create a new view of user teasers located at /sponsors/individual-sponsors that will render users with the role individual sponsor. Same output than the attendee list.
- [x] 20 elements per page or infinite scroll.
- [x] Review the styles and apply the same styles we have for the attendee list here.

**Comment by lluvigne** [comment]
WIP

**Comment by jmfernandezemergya** [comment]
WIP

**Comment by mcgarciawq** [comment]
WIP

**Comment by mcgarciawq** [comment]
Done!

**Comment by jlbellido** [comment]
Done Thanks @keilovecraft ! Looks really nice on live!

**Comment by jlbellido** [comment]
@lluvigne thanks to you as well!
