### ISSUE TITLE
[Sponsors] Fix the height of sponsor images

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#214]
We need to set a fixed height for all the sponsors images. Currently we have the problem that some silver sponsors are bigger than the gold sponsors.

**Comment by jlbellido** [comment]
@Nesta @keilovecraft What do you think we could do here?

**Comment by mcgarciawq** [comment]
WIP

**Comment by jlbellido** [comment]
Review with the current sponsors, we have some square logos. http://seville2017.drupaldays.org/sponsors
http://seville2017.drupaldays.org/program/sprints

**Comment by mcgarciawq** [comment]
:man_artist:

**Comment by jlbellido** [comment]
Thanks @keilovecraft , I've just pushed the presets as we decided. SInce this has a big impact on the sponsors section. I'm waiting to the feedback from the team. If this is ok from their side, I'll clode this ticket. Thanks!!!

**Comment by jlbellido** [comment]
Alll good Yeahh! Thanks! @keilovecraft !
