### ISSUE TITLE
[Sessions] Selected sessions list

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#216]
We need to display the selected sessions list.
We need the following changes:
- [x] New page with all published and accepted sessions.
- [x] We need to apply the same styles than the submitted sessions list.

**Comment by dimaro** [comment]
I will work on it this evening!

**Comment by jlbellido** [comment]
Thanks @dmarrufo , I knew that you are still loving me. Thanks for this present at the Valentine's Day !! I hope we can continue our love history :heartpulse:

**Comment by dimaro** [comment]
OMG! @jlbellido My heart only belongs to you.. (L)
