### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by mcgarciawq** [AsociacionDrupalES/landing#22]

**Comment by jlbellido** [comment]
@keilovecraft podemos centrar un poco más la caja de la newsleter en las paginas de error? Creo que queda un poco raro.

Gracias!!!
![error_pages-bug](https://cloud.githubusercontent.com/assets/1301237/20322789/a31c4f38-ab7a-11e6-8809-224cb44ce9b4.png)

**Comment by mcgarciawq** [comment]
En los cambios de la issue #32 se ha subido este cambio con algunos estilos básicos.
