### ISSUE TITLE
Problem with videos

### ISSUE THREAD

**Issue by penyaskito** [AsociacionDrupalES/landing#234]
@pakmanlh reported this

**Comment by penyaskito** [comment]
![img_20170211_174314](https://cloud.githubusercontent.com/assets/516163/22855493/93f7ffc4-f081-11e6-88db-a2b3ad984b0f.jpg)

**Comment by mcgarciawq** [comment]
@jlbellido :man_dancing:

**Comment by jlbellido** [comment]
@keilovecraft Tested locally and works like a charm! Thanks for this present on San Valentine's Day! This is much better than a Love Bear! :bear:
