### ISSUE TITLE
[Front] Styles for basic pages.

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#25]
We need to review the basic pages from the front-end side.

**How to reproduce:**
- Create a node of type basic page.
- Provide a title and a sample body text.
- Check the styles.

**Comment by rafavermo** [comment]
I'm working in this task but I have no permissions to assign me. @jlbellido

**Comment by jlbellido** [comment]
![25_success_test](https://cloud.githubusercontent.com/assets/1301237/20323196/12a21012-ab7c-11e6-9fbf-b40ce2f81eee.png)

I think it's fine for a first iteration, we'll review this again once the designs are finished. Thanks for your work here @rafavermo !

**Comment by jlbellido** [comment]
We'll work in a separate issue to adapt the basic pages to the final design.
