### ISSUE TITLE
[Program] Program pages.

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#251]
- [x] Menu top block with the program days.
- [x] Block Icon leyend.
- [x] Paragraph - Row
- [x] Paragraph - room/session

**How to reproduce:**

1. Create a keynote node
2. Create 2 sessions.
3. Create some menu items at admin/structure/menu/manage/schedule-menu
4. Create a Schedule node as follows in order to reproduce the different scenarios we'll have:

- Provide a title.
- First schedule row (Situation: Lunch breaks, Coffee breaks, Registration):
  - Provide a Start-end period as: 00:00 - 00:00
  - Click on "Check in case of a non sessions period"
  - Provide a Break title and description.
- Second schedule row (Situation : Key notes)
  - Provide a Start-end period as: 00:00 - 00:00
  - In the autocomplete field provide a Keynote  node.
- Third schedule row (Situation: 2 sessions at the same time)
  - Provide a Start-end period as: 00:00 - 00:00
  - In the autocomplete field provide 2 sessions.
- Forth schedule row (Situation: 1 session)
  - Provide a Start-end period as: 00:00 - 00:00
  - In the autocomplete field provide 1 session.

**Notes**
- We are using paragraphs for add new slots (Date ranges) with different situations.
- For rendering sessions and keynotes we are using a new view mode "program"
- Designs can be found at at invision.
- I've created a page example at the staging environment (Check the content list.)

**Comment by jlbellido** [comment]
Done the backend configuration. Now we need the awesome work from the frontend side.

**Comment by jlbellido** [comment]
Added the sections: "How to reproduce" and Notes. It is ready to be styled.

**Comment by mcgarciawq** [comment]
Done! 🤙

**Comment by jlbellido** [comment]
@keilovecraft  Looks awesoma! We still need to review the mobile version. But looks really promising !

**Comment by jlbellido** [comment]
AWESOME work @keilovecraft with the styling. Thanks to everybody that was involved here: @ckrina @keilovecraft you rule!
