### ISSUE TITLE
[User - Register] Register form

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#29]
- As user I want to create a new account in the web page and specify the following data:
  - Full Name
  - Drupal.org nick name
  - Drupal.org profile link
- The picture will be available at the normal user edit form.
- As user I want to receive a custom email in order to confirm my email when I sign up via the register form.
- As user I want to have the role "attendee" automatically once that I’ve been registered on the platform. 

**Open points**

Backend:
- [ ] Email texts for the users.

Frontend:
- [ ] Apply the same styles than the contact form.

**Comment by jlbellido** [comment]
Working on this.

**Comment by jlbellido** [comment]
Ready to be reviewed by the front-end team.

**How to reproduce:**
* Enable the register form at /admin/config/people/accounts . 
* Go to /user/register.

**Comment by jlbellido** [comment]
We need to review the status of this.

**Comment by jlbellido** [comment]
I've checked this task, added some open points but they don't block the frontend part.

**Comment by Nesta** [comment]
WIP

**Comment by Nesta** [comment]
Done, but I think .... the tabs are very ugly no?....

**Comment by jlbellido** [comment]
We can improve the tabs the next sprint. It is fine by the moment. Thanks @Nesta !
