### ISSUE TITLE
Attendees list

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#30]
- As user I want to check all the attendees that will attend to the event with an infinite scroll.
- As user I want to see a default nice pirate picture for each attendee in case it is not provided by the user.
- As user I want to see by attendee a picture and the drupal.org nickname linking to the d.o profile.
- As user I want see the total number of attendees of the event.

**Comment by dimaro** [comment]
Hi!, I will work on this.

**Comment by jlbellido** [comment]
**How to reproduce**
* Create some users with the attendee role.
* Go to / attendees


This can be reviewed by the front-end team

**Comment by jlbellido** [comment]
We need to review the status of this. Specially if the attendees list fits with the current design https://projects.invisionapp.com/share/7K9PLICYJ#/screens/214656315

**Comment by jlbellido** [comment]
I'm reviewing this.

**Comment by jlbellido** [comment]
Reviewed and adapted to the design. This is ready to be styled.

**Comment by jlbellido** [comment]
Tested and looks fine! Thanks @babette-landmesser !
