### ISSUE TITLE
[Sponsors] Sponsors list

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#32]
As user I want to see all sponsors of the event. Categorized by sponsor level starting with the top sponsors.

**Comment by jlbellido** [comment]
Starting with this task.

**Comment by jlbellido** [comment]
Created the required blocks for each sponsors ship level, placed them under /sponsors page.

**Comment by jlbellido** [comment]
**How to reproduce locally:**
- Create a several sponsors from node/add, you can use devel generate for this.
- Create a basic page and put as url alias "/sponsors".
- You'll be able to see at the bottom all sponsors categorized by level at the basic page you created before.

@keilovecraft , this need to have a basic styling.

Thanks!

**Comment by mcgarciawq** [comment]
Take a look @jlbellido , now you can place a carrousel and give it back to me :)

**Comment by jlbellido** [comment]
Looks really nice now! Thanks @keilovecraft . We'll move this ticket to the backlog until having a final design.

**Comment by jlbellido** [comment]
Closing thios task in favor of the open points.

Big thanks to @keilovecraft for your work here!
