### ISSUE TITLE
[Sponsors] Become a sponsor page

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#35]
As user I want to know what are the different possibilities for sponsoring the event. This page will have a main text that summarizes the sponsoring information and a link where I'll be able to download the sponsorship documentation.

**Comment by jlbellido** [comment]
We'll create  the "Become a sponsor page" with the basic page content type. But we need to have a field for uploading files.

**Comment by lluvigne** [comment]
Working on it!

**Comment by jlbellido** [comment]
Ok, we have the file there. Thanks @lluvigne . I'll move this ticket to the backlog until have a final design.

**Comment by jlbellido** [comment]
We'll use the same page than sponsors. This is not longer needed. Thanks @lluvigne
