### ISSUE TITLE
[News] Most important news block

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#44]
As user I want to see the most important news in a block placed in the home page.

**Comment by lluvigne** [comment]
I will work on this, but this issue depend on #45 in order to build the block on the same view.

**Comment by jlbellido** [comment]
Let's use a different view mode for this. Instead of the teaser. May be "highlighted" ??

Other is fine, tested and working. Thanks @lluvigne !

**Comment by jlbellido** [comment]
Ready for applying some basic styles. 

**How to reproduce:**
* Create some news and check the "sticky on the lists" option.
* Go to the home and you'll be able to see the highlighted news from the DDDays

**Comment by jlbellido** [comment]
This is done already, thanks @ckrina it is really awesome!
