### ISSUE TITLE
[News] News list

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#45]
- As user I want to see the latest news of the event in a list.

**Comment by dimaro** [comment]
I'm working on it!

**Comment by jlbellido** [comment]
Tested and working the basics. We'll have to review this again once that we have the final design. Meanwhile we can apply some basic styles.

Thanks!

**Comment by jlbellido** [comment]
We need to adapt the news list to the given design (https://projects.invisionapp.com/share/7K9PLICYJ#/screens/214488110)

The changes are the following:

Backend:

- [x] Display to published date with a correct format.

Frontend
- [x] Adapt the styles to the design.

**Comment by babette-landmesser** [comment]
I'll do the frontend stuff now.

**Comment by jlbellido** [comment]
Thank @babette-landmesser ! Now the only thing pending is the backend part.

**Comment by lluvigne** [comment]
WIP

**Comment by jlbellido** [comment]
Thanks  @lluvigne ! This is solved now
