### ISSUE TITLE
[Jobs] As user I want to see a list of the offers available on the event.

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#56]
As user I want to see a list of the offers available on the event. For each job offer I want to see the following data:

- The title of the offer linking to the detailed offer..
- The company logo linked to their web page.
- A trimmed version of the offer or its summary.
- A link "Read more" linking to the detailed job offer.

**Comment by jlbellido** [comment]
Ready to be reviewed by the front-end team.

**Comment by rafavermo** [comment]
WIP

**Comment by mcgarciawq** [comment]
Ready! :dancer:

**Comment by jlbellido** [comment]
tested and looks really nice to me! Thanks @keilovecraft @rafavermo for you awesome work!
