### ISSUE TITLE
[Jobs] As user I want to see the detailed description of a Job offer.

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#57]
As user I want to see the detailed description of a Job offer. I want to see the following data for a job offer:
- The title of the job
- The logo of the company linked to their webpage.
- The full version of the job's body.

**Comment by jlbellido** [comment]
This can be reviewed by the front-end team.

**Comment by mcgarciawq** [comment]
WIP :icecream:

**Comment by mcgarciawq** [comment]
Ready for you @jlbellido :unicorn:

**Comment by jlbellido** [comment]
WOW! Thanks @keilovecraft ! :1st_place_medal:
