### ISSUE TITLE
[Call for papers] As registered user I want to send a session.

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#58]
As registered user I want to send a session or training proposal for the event. I want to specify the following data about my proposed session.

- Title of my session.
- Description of my session.
- Experience level needed: (Beginner, Intermediate, Advanced)
- Speaker/s : Reference to the users registered.
- Type: (Session or Workshop)
- Topic: (Case studies, Development, DevOps, Frontend, Performances, Site building, Other)

Frontend:

- [x] Add styles for the Add session form following https://projects.invisionapp.com/share/7K9PLICYJ#/screens/214488310
- [x] Review them for the edit form.

Backend:

- [x] Customize the content type with the fields and texts as they are on the designs.

**How to reproduce:**
As admin user of attendee user go to node/add/session

**Comment by jlbellido** [comment]
Starting this task

**Comment by jlbellido** [comment]
We need to check the status of this task and match it with the given designs https://projects.invisionapp.com/share/7K9PLICYJ#/screens/214488310

**Comment by jlbellido** [comment]
Starting this

**Comment by jlbellido** [comment]
Submitted the backend part, now the front-end part can be done.

**Comment by mcgarciawq** [comment]
WIP 👍

**Comment by mcgarciawq** [comment]
@jlbellido can you review and close this issue if everything's ok?

**Comment by jlbellido** [comment]
Looks really nice! Attaching a screenshot
![add-edit-session-form](https://cloud.githubusercontent.com/assets/1301237/22332674/62ea12ca-e3d2-11e6-8189-c40d13c1d2a8.png)

Thanks @keilovecraft for your awesome work!
