### ISSUE TITLE
[Call for papers] As user I want to check all submitted  sessions

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#59]
As user I want to check all submitted  sessions. The list will look like a table. For each session I want to see the following information:

- Title of the talk linking t the detailed proposal.
- Experience level.
- Speaker(s). Linking to their Drupal.org account.

On the other hand, I want to be able to filter by (Title & Experience level)

**Comment by jlbellido** [comment]
We need to check the status of this. And match it with the given design  https://projects.invisionapp.com/share/7K9PLICYJ#/screens/214489043

**Comment by jlbellido** [comment]
Reviewing this ticket.

**Comment by jlbellido** [comment]
Reviewed and adapted the session list to the design and customized the session teaser. This is ready to be styled.

**Comment by Nesta** [comment]
WIP

**Comment by mcgarciawq** [comment]
WIP - nesta out :P
