### ISSUE TITLE
[Global] Footer

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/landing#73]
We need to finish the footer region in terms of styling. Currently the blocks and texts are placed and the regions created.

Please check the designs in advance.

**Comment by jlbellido** [comment]
Starting this

**Comment by jlbellido** [comment]
Approved some changes, but it is need to finish it.

**Comment by babette-landmesser** [comment]
Christoph is working on that.

**Comment by jlbellido** [comment]
How to reproduce locally:

- Add some menu items at: /admin/structure/menu/manage/footer-left-menu

**Comment by cgahmann** [comment]
I start it.

**Comment by jlbellido** [comment]
We still need to review the footer menu because the menu items are a little bit hidden.
![footer_menu_hidden](https://cloud.githubusercontent.com/assets/1301237/21953921/7259e52e-da44-11e6-9e52-e013c81dbec8.png)

**Comment by babette-landmesser** [comment]
The footer menu should now have enough space so that the menu items are readable. But on basic pages, the lines from the background image should not be visible. This is not done yet.

**Comment by jlbellido** [comment]
I'm closing this ticket and we'll work on the pending topics in separated tickets: #105 and #104

Thanks @babette-landmesser for your work here!
